version: '3.7'

volumes:
  maria_vol:

networks:
  maria_net:
    driver: bridge


services:
  mariadb:
    image: mariadb:10.6
    restart: always
    volumes:
      - maria_vol:/var/lib/mysql
    networks:
      - maria_net
    ports:
     - 3306:3306
    environment:
     MARIADB_USER: mariauser 
     MARIADB_PASSWORD: mariapwd
     MARIADB_ROOT_PASSWORD: mariapwd 

  phpmyadmin:
    image: phpmyadmin:5.2.0
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      - maria_net
